# Global
site_url: https://ncrocfer.github.io
site_title: ncrocfer
theme: default
auto_expand: True

# Static folders
static_dirs:
    - images

# Urls
post_url: '{year}/{month}/{day}/{slug}'
page_url: '{slug}'
category_url: 'categories/{category}'
tag_url: 'tags/{tag}'
author_url: 'authors/{author}'

# Authors
authors:
    ncrocfer:
        name: Nicolas Crocfer
        email: ncrocfer [at] gmail [dot] com
        web: https://ncrocfer.github.io

# Pure theme
tagline: 'Python & Web security'
cover_bg_color: 0D302E
google_analytics: UA-65778407-1
social:
    github: https://github.com/ncrocfer
    twitter-square: https://twitter.com/ncrocfer
